package com.recipes.srd.recipes.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.recipes.srd.recipes.db.Recipe;
import com.recipes.srd.recipes.db.Submenu;
import com.recipes.srd.recipes.db.UpdateCheck;

import com.recipes.srd.recipes.db.RecipeDao;
import com.recipes.srd.recipes.db.SubmenuDao;
import com.recipes.srd.recipes.db.UpdateCheckDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recipeDaoConfig;
    private final DaoConfig submenuDaoConfig;
    private final DaoConfig updateCheckDaoConfig;

    private final RecipeDao recipeDao;
    private final SubmenuDao submenuDao;
    private final UpdateCheckDao updateCheckDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recipeDaoConfig = daoConfigMap.get(RecipeDao.class).clone();
        recipeDaoConfig.initIdentityScope(type);

        submenuDaoConfig = daoConfigMap.get(SubmenuDao.class).clone();
        submenuDaoConfig.initIdentityScope(type);

        updateCheckDaoConfig = daoConfigMap.get(UpdateCheckDao.class).clone();
        updateCheckDaoConfig.initIdentityScope(type);

        recipeDao = new RecipeDao(recipeDaoConfig, this);
        submenuDao = new SubmenuDao(submenuDaoConfig, this);
        updateCheckDao = new UpdateCheckDao(updateCheckDaoConfig, this);

        registerDao(Recipe.class, recipeDao);
        registerDao(Submenu.class, submenuDao);
        registerDao(UpdateCheck.class, updateCheckDao);
    }
    
    public void clear() {
        recipeDaoConfig.clearIdentityScope();
        submenuDaoConfig.clearIdentityScope();
        updateCheckDaoConfig.clearIdentityScope();
    }

    public RecipeDao getRecipeDao() {
        return recipeDao;
    }

    public SubmenuDao getSubmenuDao() {
        return submenuDao;
    }

    public UpdateCheckDao getUpdateCheckDao() {
        return updateCheckDao;
    }

}
